# Generated by Django 4.1.6 on 2023-03-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Character Names', max_length=100)),
                ('picture', models.TextField(help_text='Character Images')),
            ],
        ),
    ]
