# Generated by Django 4.1.6 on 2023-04-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the book.', max_length=70)),
                ('image', models.TextField(help_text='Image for Books')),
                ('rating', models.IntegerField(help_text='The the reviewer has given.')),
                ('author', models.CharField(help_text='The name of Author', max_length=70)),
                ('price', models.IntegerField(help_text='Price of book')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
